Repository parosly/parosly, pull requests merged in 2025-01, with the labels that each got.

#13 feat(UI): add loading indicator to export
  ui/pages/reports/index.html
  ui/pages/reports/script.js
  ui/pages/reports/style.css
Labels: enhancement

#14 Release v0.1.1
  .github/workflows/release.yml
  README.md
  src/api/v1/endpoints/docs.py
  src/models/config.py
  src/schemas/configs.json
  ui/pages/reports/index.html
  ui/pages/reports/script.js
  ui/pages/reports/style.css
Labels: bug, enhancement, dependencies

#16 feat(api): Enable Web UI by default
  CONTRIBUTING.md
  README.md
  docs/examples/docker/docker-compose.yml
  docs/examples/kubernetes/helm/values.yaml
  src/utils/arguments.py
Labels: enhancement

#18 fix(api): Set httpx timeout value to 'never'
  src/api/v1/endpoints/reverse_proxy.py
Labels: bug

#19 fix(schemas): Add filter_external_labels property under remote_read setting
  src/schemas/configs.json
Labels: bug
